apiVersion: v1
kind: ConfigMap

metadata:
  name: banking-config
  namespace: banking

data:

  ACCOUNT_SERVICE_URL: "http://account-service:5001/account"

  PAYMENT_SERVICE_URL: "http://payment-service:5002/payments"

  TRANSACTION_SERVICE_URL: "http://transaction-service:5003/transactions"